services:
#    p_hu_n_platform.example:
#        class: PHuN\PlatformBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    phun_platform.antispam:
        class: PHuN\PlatformBundle\Antispam\PHuNAntispam
        arguments: [@mailer, %locale%, 50]

    phun_user.registration_listener:
        class: PHuN\PlatformBundle\EventListener\RegistrationListener
        arguments: []
        tags:
            - { name: kernet.event_subscriber }
    
    phun_editor.config:
        class: PHuN\PlatformBundle\Editor\EditorConfig
        #arguments: [@listPlugins, @stylesheet]
        
    phun_diff.match:
        class: diffMatchPatch\src\DiffMatchPatch
        
    comment_service: 
        class: PHuN\PlatformBundle\Controller\CommentController
#        arguments: ["@doctrine.orm.entity_manager"]