<?php

namespace PHuN\PlatformBundle\Entity;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
	public function getApplicationsWithAdvert(array $advAuthor)
	{
		$qb = $this->createQueryBuilder('a');

		// On fait une joinure avec l'entité Advert avec pour alias "adv"
		$qb
			->join('a.advert', 'adv')
			->addSelect('adv')
		;

		// Puis on ne retourne que $limit résultats
		//$qb->setMaxResults($limit);
		// Puis on filtre sur le nom des catégories à l'aide d'un IN 
  		$qb->where($qb->expr()->in('adv.author', $advAuthor));

		// Enfin, on retourne le résultat
		return $qb
			->getQuery()
			->getResult()
		;	
	}
}
