<?php

namespace PHuN\PlatformBundle\Entity;

/**
 * CorpusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorpusRepository extends \Doctrine\ORM\EntityRepository
{
}
