<?php

namespace PHuN\PlatformBundle\Entity;

/**
 * DtdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DtdRepository extends \Doctrine\ORM\EntityRepository
{
}
