<?php

namespace PHuN\PlatformBundle\Entity;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
	public function myFindAll()
	{
		return $this
		    ->createQueryBuilder('p')
		   	->getQuery()
		   	->getResult()
		;
	}

	public function myFindLimited($limit)
	{
		$qb = $this->createQueryBuilder('p');
	  	//for ($i = 1; $i <= 100; $i++) {

		    
	  	$qb
	  		->setMaxResults($limit);
	  	;

	  	return $qb
	  		->getQuery()
	  		->getResult()
	  	;	
	    //}
	}
  	
}
