<?php

namespace PHuN\PlatformBundle\Entity;

/**
 * SousDossierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousDossierRepository extends \Doctrine\ORM\EntityRepository
{
}
