<?php

namespace PHuN\PlatformBundle\Entity;

/**
 * StylesheetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StylesheetRepository extends \Doctrine\ORM\EntityRepository
{
}
