<?php

namespace PHuN\PlatformBundle\Entity;

/**
 * TranscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TranscriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
