<?php

namespace PHuN\PlatformBundle\Entity;

/**
 * TranscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TranscriptionRepository extends \Doctrine\ORM\EntityRepository
{
	// public function findByUser($user)
	// {
	//   $qb = $this->createQueryBuilder('t');

	//   $qb->where('t.user = :user_id')
	//        ->setParameter('user', $user)
	//      ->orderBy('t.date', 'DESC')
	//   ;

	//   return $qb
	//     ->getQuery()
	//     ->getResult()
	//   ;
	// }
    
    public function getMostRecentTranscriptionForPage($pageId)
    {
        return $this
            ->createQueryBuilder('t')
            ->where('t.page == :page')
            ->setParameter('page', $pageId)    
            ->orderBy('t.date', 'DESC')
            ->getQuery()
            ->getArrayResult()
        ;
    }
}
